//
//  SessionAIService.swift
//  ClinicalAnon
//
//  Purpose: AI chat service for live session assistance
//  Organization: 3 Big Things
//

import Foundation

// MARK: - Session AI Service

@MainActor
class SessionAIService: ObservableObject {

    // MARK: - Published State

    @Published var includeTranscriptContext: Bool = true
    @Published private(set) var isProcessing: Bool = false
    @Published private(set) var error: AppError?

    // MARK: - Dependencies

    private let bedrockService: BedrockService
    private let credentialsManager: AWSCredentialsManager

    // MARK: - Constants

    private let maxContextTokens = 10000
    private let tokensPerWord = 1.3

    // MARK: - System Prompt

    private let systemPrompt = """
    You are a clinical psychology AI assistant helping a clinician during a live therapy session in New Zealand.

    ## About This Transcript

    This transcript was generated by automatic speech recognition (Whisper) from a live recording. Be aware:

    - **Transcription errors are expected**: Misspellings of names, clinical terms, and NZ place names are common
    - **Phonetic confusion**: Names may appear as phonetic variants (Sean/Shawn/Shaun, Māori names may be mangled)
    - **Natural speech**: Expect filler words (um, uh, like, you know), false starts, self-corrections, and repetition
    - **Incomplete sentences**: People don't speak in complete sentences — follow meaning, not grammar
    - **Speaker labels**: [Clinician] = microphone audio, [Other] = system audio (video call participant). Attribution may be imperfect during overlapping speech
    - **[Gap] markers**: Indicate pauses, silence, or sections where audio was unclear

    When you encounter unclear or garbled text, infer likely meaning from context rather than treating it literally.

    ## Your Role

    - Answer clinical questions about the session
    - Summarise key themes, concerns, or dynamics
    - Suggest therapeutic approaches or follow-up questions
    - Identify patterns across the conversation
    - Maintain professional, evidence-informed clinical language

    Do NOT:
    - Diagnose the client
    - Make assumptions about demographics from redacted information
    - Provide advice that contradicts established therapeutic frameworks

    ## Privacy & Redaction

    - Identifying information appears as codes: [PERSON_A], [LOCATION_A], [DATE_A], [ORG_A], etc.
    - These are real detected entities — treat them as meaningful references, not placeholders
    - The same code (e.g., [PERSON_A]) refers to the same entity throughout
    - Never speculate about the original values behind redaction codes
    - If you need to reference someone, use their code (e.g., "When [PERSON_A] mentioned...")
    """

    // MARK: - Initialization

    init(bedrockService: BedrockService, credentialsManager: AWSCredentialsManager) {
        self.bedrockService = bedrockService
        self.credentialsManager = credentialsManager
    }

    // MARK: - Public Methods

    /// Send a message to the AI and get a response
    func sendMessage(_ message: String, session: LiveSession) async throws -> String {
        guard bedrockService.isConfigured else {
            throw AppError.aiNotConfigured
        }

        isProcessing = true
        error = nil

        defer { isProcessing = false }

        // Add user message to conversation context
        session.conversationContext.addUserMessage(message)

        // Build system prompt with optional transcript context
        var fullSystemPrompt = systemPrompt

        if includeTranscriptContext {
            let transcriptContext = prepareTranscriptContext(for: session)
            if !transcriptContext.isEmpty {
                fullSystemPrompt += """

                ## Current Session Transcript

                \(transcriptContext)
                """
            }
        }

        // Get messages for API
        let messages = session.conversationContext.getMessagesForAPI()

        do {
            let response = try await bedrockService.invoke(
                systemPrompt: fullSystemPrompt,
                messages: messages,
                model: credentialsManager.selectedModel,
                maxTokens: 2048
            )

            // Record assistant response in context
            session.conversationContext.addAssistantMessage(response)

            // Add to session's chat messages for UI
            session.chatMessages.append(ChatMessage.user(message))
            session.chatMessages.append(ChatMessage.assistant(response))

            return response

        } catch {
            let appError = AppError.aiProcessingFailed(error.localizedDescription)
            self.error = appError
            throw appError
        }
    }

    /// Prepare transcript context with token truncation
    func prepareTranscriptContext(for session: LiveSession) -> String {
        guard !session.transcriptSegments.isEmpty else {
            return ""
        }

        let transcript = session.redactedTranscript
        let wordCount = transcript.split(separator: " ").count
        let estimatedTokens = Int(Double(wordCount) * tokensPerWord)

        if estimatedTokens <= maxContextTokens {
            return transcript
        }

        // Truncate: keep most recent segments
        var accumulated: [TranscriptSegment] = []
        var tokenCount = 0

        for segment in session.transcriptSegments.reversed() {
            let segmentWordCount = segment.text.split(separator: " ").count
            let segmentTokens = Int(Double(segmentWordCount) * tokensPerWord)

            if tokenCount + segmentTokens > maxContextTokens {
                break
            }

            accumulated.insert(segment, at: 0)
            tokenCount += segmentTokens
        }

        let truncatedTranscript = accumulated.map { segment in
            "[\(segment.speaker.label)] \(segment.text)"
        }.joined(separator: "\n\n")

        return "[Earlier content truncated]\n\n" + truncatedTranscript
    }

    /// Reset the conversation context
    func resetContext(for session: LiveSession) {
        session.conversationContext.reset()
        session.chatMessages.removeAll()
    }
}
