//
//  ClinicalNotesView.swift
//  Redactor Lite
//
//  Purpose: Displays clinical notes generated by Cowork with entity substitution.
//           Reads clinical_notes.json from session folder, substitutes entity codes
//           with real names from Private/ entity map for display only.
//

import SwiftUI
import AppKit

// MARK: - Clinical Notes Model

struct ClinicalNotes: Codable {
    var session_id: String?
    var generated_at: String?
    var sections: Sections?

    struct Sections: Codable {
        var clinical_notes: String?
        var client_summary: String?
        var clinical_review: String?
    }
}

// MARK: - Color Palette (matches dashboard)

private enum NotesColors {
    static let background = Color(red: 250/255, green: 247/255, blue: 244/255)
    static let cardBg = Color.white
    static let cardBorder = Color(red: 46/255, green: 46/255, blue: 46/255).opacity(0.12)
    static let cardShadow = Color.black.opacity(0.06)
    static let textPrimary = Color(red: 46/255, green: 46/255, blue: 46/255)
    static let textSecondary = Color(red: 60/255, green: 60/255, blue: 67/255).opacity(0.6)
    static let textDim = Color(red: 60/255, green: 60/255, blue: 67/255).opacity(0.35)
    static let teal = Color(red: 10/255, green: 107/255, blue: 124/255)
}

// MARK: - Card Modifier

private extension View {
    func notesCard() -> some View {
        self
            .background(NotesColors.cardBg)
            .clipShape(RoundedRectangle(cornerRadius: 14))
            .overlay(
                RoundedRectangle(cornerRadius: 14)
                    .stroke(NotesColors.cardBorder, lineWidth: 1)
            )
            .shadow(color: NotesColors.cardShadow, radius: 8, x: 0, y: 2)
    }
}

// MARK: - Clinical Notes View

struct ClinicalNotesView: View {

    let sessionFolder: URL?
    let privateFolderURL: URL?

    @State private var notes: ClinicalNotes?
    @State private var entityMap: [String: String] = [:]
    @State private var timer: Timer?
    @State private var copyFeedback: String?

    var body: some View {
        ZStack {
            NotesColors.background.ignoresSafeArea()

            if let notes = notes, notes.sections != nil {
                notesBody(notes)
            } else {
                waitingState
            }
        }
        .onAppear {
            loadNotes()
            timer?.invalidate()
            let t = Timer(timeInterval: 2, repeats: true) { _ in
                Task { @MainActor in
                    loadNotes()
                }
            }
            RunLoop.main.add(t, forMode: .common)
            timer = t
        }
        .onDisappear {
            timer?.invalidate()
            timer = nil
        }
    }

    // MARK: - Data Loading

    private func loadNotes() {
        guard let folder = sessionFolder else { return }
        let url = folder.appendingPathComponent("clinical_notes.json")
        guard let data = try? Data(contentsOf: url) else { return }
        do {
            notes = try JSONDecoder().decode(ClinicalNotes.self, from: data)
        } catch {
            print("[ClinicalNotes] Failed to decode: \(error)")
        }

        guard let privateFolder = privateFolderURL else { return }
        let mapURL = privateFolder.appendingPathComponent("entity_map.json")
        if let mapData = try? Data(contentsOf: mapURL),
           let mapJSON = try? JSONSerialization.jsonObject(with: mapData) as? [String: Any],
           let mappings = mapJSON["mappings"] as? [String: String] {
            entityMap = mappings
        }
    }

    /// Substitute entity codes with real names for display
    private func sub(_ text: String) -> String {
        var result = text
        let sorted = entityMap.sorted { $0.key.count > $1.key.count }
        for (code, name) in sorted {
            result = result.replacingOccurrences(of: "[\(code)]", with: name)
            result = result.replacingOccurrences(of: code, with: name)
        }
        return result
    }

    // MARK: - Waiting State

    private var waitingState: some View {
        VStack(spacing: 12) {
            ProgressView()
                .scaleEffect(0.8)
                .tint(NotesColors.teal)
            Text("Waiting for clinical notes\u{2026}")
                .font(.system(size: 13))
                .foregroundColor(NotesColors.textDim)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // MARK: - Notes Body

    private func notesBody(_ notes: ClinicalNotes) -> some View {
        VStack(spacing: 0) {
            // Header with copy all button
            HStack {
                Text("Clinical Notes")
                    .font(.system(size: 18, weight: .semibold))
                    .foregroundColor(NotesColors.textPrimary)
                if let ts = notes.generated_at {
                    Text(formatTimestamp(ts))
                        .font(.system(size: 12))
                        .foregroundColor(NotesColors.textDim)
                }
                Spacer()
                if let feedback = copyFeedback {
                    Text(feedback)
                        .font(.system(size: 11))
                        .foregroundColor(NotesColors.teal)
                        .transition(.opacity)
                }
                Button("Copy All") {
                    copyAll(notes)
                }
                .buttonStyle(.plain)
                .font(.system(size: 12, weight: .medium))
                .foregroundColor(NotesColors.teal)
                .padding(.horizontal, 12)
                .padding(.vertical, 6)
                .background(NotesColors.teal.opacity(0.1))
                .cornerRadius(6)
            }
            .padding(.horizontal, 20)
            .padding(.top, 16)
            .padding(.bottom, 12)

            // Scrollable sections
            ScrollView {
                VStack(spacing: 12) {
                    if let text = notes.sections?.clinical_notes {
                        sectionCard("Clinical Record", text: text, icon: "doc.text")
                    }
                    if let text = notes.sections?.client_summary {
                        sectionCard("Client Summary", text: text, icon: "person")
                    }
                    if let text = notes.sections?.clinical_review {
                        sectionCard("Clinical Review", text: text, icon: "exclamationmark.triangle")
                    }
                }
                .padding(.horizontal, 20)
                .padding(.bottom, 16)
            }
        }
    }

    // MARK: - Section Card

    private func sectionCard(_ title: String, text: String, icon: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Image(systemName: icon)
                    .font(.system(size: 12))
                    .foregroundColor(NotesColors.teal)
                Text(title)
                    .font(.system(size: 14, weight: .semibold))
                    .foregroundColor(NotesColors.textPrimary)
                Spacer()
                Button {
                    copySection(title: title, text: text)
                } label: {
                    HStack(spacing: 3) {
                        Image(systemName: "doc.on.doc")
                            .font(.system(size: 10))
                        Text("Copy")
                            .font(.system(size: 11))
                    }
                    .foregroundColor(NotesColors.textSecondary)
                }
                .buttonStyle(.plain)
            }
            .padding(.horizontal, 14)
            .padding(.top, 14)

            Text(sub(text))
                .font(.system(size: 13))
                .foregroundColor(NotesColors.textPrimary)
                .lineSpacing(4)
                .textSelection(.enabled)
                .padding(.horizontal, 14)
                .padding(.bottom, 14)
        }
        .notesCard()
    }

    // MARK: - Copy Actions

    private func copySection(title: String, text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(sub(text), forType: .string)
        showCopyFeedback("Copied \(title)")
    }

    private func copyAll(_ notes: ClinicalNotes) {
        var parts: [String] = []
        if let text = notes.sections?.clinical_notes {
            parts.append("CLINICAL RECORD\n\n\(sub(text))")
        }
        if let text = notes.sections?.client_summary {
            parts.append("CLIENT SUMMARY\n\n\(sub(text))")
        }
        if let text = notes.sections?.clinical_review {
            parts.append("CLINICAL REVIEW\n\n\(sub(text))")
        }
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(parts.joined(separator: "\n\n---\n\n"), forType: .string)
        showCopyFeedback("Copied all sections")
    }

    private func showCopyFeedback(_ message: String) {
        withAnimation { copyFeedback = message }
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            withAnimation { copyFeedback = nil }
        }
    }

    // MARK: - Helpers

    private func formatTimestamp(_ iso: String) -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        if let date = formatter.date(from: iso) {
            let display = DateFormatter()
            display.dateFormat = "d MMM yyyy, h:mm a"
            return display.string(from: date)
        }
        // Try without fractional seconds
        formatter.formatOptions = [.withInternetDateTime]
        if let date = formatter.date(from: iso) {
            let display = DateFormatter()
            display.dateFormat = "d MMM yyyy, h:mm a"
            return display.string(from: date)
        }
        return iso
    }
}
